title: Page
icon: file-text-o 
pages: true
files:
  fields:
    copyright: copyright
    description: description
    caption: caption
fields:
  title: title
  description: description
  text: text
  line: line
  seotitle: seotitle
